# Generated by Django 3.0.3 on 2020-04-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200328_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next',
        ),
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
    ]
