# Generated by Django 3.0.4 on 2020-03-09 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('a_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a_email', models.EmailField(max_length=50)),
                ('a_host', models.URLField(max_length=50)),
                ('a_url', models.URLField(max_length=50)),
                ('a_github', models.URLField(max_length=50)),
                ('a_lastname', models.CharField(max_length=30)),
                ('a_firstname', models.CharField(max_length=30)),
                ('a_description', models.TextField(blank=True, max_length=200, null=True)),
                ('a_birthdate', models.DateField(blank=True, null=True)),
                ('a_alias', models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), max_length=30)),
            ],
        ),
    ]
