# Generated by Django 3.0.3 on 2020-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=20),
        ),
    ]
