# Generated by Django 3.0.3 on 2020-03-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='a_alias',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='a_github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='a_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='a_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='a_url',
            new_name='url',
        ),
    ]
