# Generated by Django 3.0.3 on 2020-03-09 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), max_length=60),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
