# Generated by Django 3.0.3 on 2020-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200310_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_firstname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_gender',
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_lastname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='a_signupdate',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterModelTable(
            name='author',
            table='login',
        ),
    ]
