# Generated by Django 3.0.3 on 2020-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
