# Generated by Django 3.0.4 on 2020-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200310_2344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
