# Generated by Django 3.0.3 on 2020-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200310_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=100)),
                ('a_email', models.EmailField(max_length=60, unique=True)),
                ('a_lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('a_firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('a_description', models.TextField(blank=True, max_length=200, null=True)),
                ('a_gender', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='author',
            name='github',
        ),
        migrations.RemoveField(
            model_name='author',
            name='host',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
