# Generated by Django 3.0.3 on 2020-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20200328_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='follower',
        ),
        migrations.AddField(
            model_name='friend',
            name='followee_host',
            field=models.URLField(default='https://cmput-404-project.herokuapp.com/'),
        ),
        migrations.AddField(
            model_name='friend',
            name='followee_id',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='friend',
            name='followee_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='friend',
            name='followee_url',
            field=models.URLField(default='https://cmput-404-project.herokuapp.com/'),
        ),
        migrations.AddField(
            model_name='friend',
            name='follower_host',
            field=models.URLField(default='https://cmput-404-project.herokuapp.com/'),
        ),
        migrations.AddField(
            model_name='friend',
            name='follower_id',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='friend',
            name='follower_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='friend',
            name='follower_url',
            field=models.URLField(default='https://cmput-404-project.herokuapp.com/'),
        ),
    ]
