# Generated by Django 3.0.3 on 2020-03-10 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a_email', models.EmailField(max_length=60, unique=True)),
                ('a_lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('a_firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('a_description', models.TextField(blank=True, max_length=200, null=True)),
                ('a_gender', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
