# Generated by Django 3.0.4 on 2020-03-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(blank=True, default='Title Unknown', max_length=100)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.TextField(blank=True, default='No Description', max_length=400)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(blank=True, default='PUBLIC', max_length=30)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
