# Generated by Django 3.0.3 on 2020-03-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_type',
            field=models.IntegerField(choices=[(1, 'plaintext'), (2, 'markdown')], default='1'),
        ),
    ]
