# Generated by Django 3.0.3 on 2020-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200327_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.TextField(default='[]'),
        ),
    ]
