# Generated by Django 3.0.3 on 2020-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200310_1647'),
        ('posts', '0002_auto_20200310_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
