# Generated by Django 3.0.3 on 2020-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200327_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='next',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
