# Generated by Django 3.0.3 on 2020-03-21 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20200320_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='another_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
