# Generated by Django 3.0.3 on 2020-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual', models.BooleanField(default=False)),
                ('not_read', models.BooleanField(default=True)),
            ],
        ),
    ]
