# Generated by Django 3.0.3 on 2020-03-24 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FOAF_another_friend', to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_FOAF_friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FOAF_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
