# Generated by Django 3.0.3 on 2020-03-15 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0006_auto_20200315_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='not_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='rec_follow_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='req_follow_rec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
